version: 2.1
orbs:
    node: circleci/node@4.1.0
    aws-cli: circleci/aws-cli@1.3.1
jobs:
    build:
        docker:
            - image: "cimg/base:stable"
        steps:
            - node/install
            - checkout
            - run:
                  name: Install Front-End
                  command: |
                      npm run frontend:install
            - run:
                  name: Build Front-End
                  command: |
                      npm run frontend:build
    deploy:
        docker:
            - image: "cimg/base:stable"
        steps:
            - node/install
            - checkout
            - aws-cli/setup
            - run:
                  name: Deploy Front-End
                  command: |
                      npm run frontend:deploy
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - deploy
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - deploy
